package doGet;

import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * Servlet implementation class AboutMe
 */
public class AboutMe extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public AboutMe() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.setContentType("text/html");
		response.setCharacterEncoding("utf-8");
		PrintWriter wt=response.getWriter();
		String value="<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <title>Glass morphism Profile Card</title>\r\n"
				+ "    <link rel=\"stylesheet\" href=\"style.css\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n"
				+"	   <link rel=\"stylesheet\" type=\"text/css\" href=\"//css/styleLogin.css\" />\r\n"
				+"<style>*{\r\n"
				+ "    margin: 0;\r\n"
				+ "    padding: 0;\r\n"
				+ "    font-family: 'Poppins', sans-serif;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "body{\r\n"
				+ "    background-color: #1c1c25;\r\n"
				+ "    font-family: Arial, sans-serif;\r\n"
				+ "    padding: 20px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "html, body {\r\n"
				+ "    height: 100%;\r\n"
				+ "  }\r\n"
				+ "  section{\r\n"
				+ "    height:100vh;\r\n"
				+ "    width:100%;\r\n"
				+ "    display: flex;\r\n"
				+ "    flex-direction: column;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    align-items: center;\r\n"
				+ "  }\r\n"
				+ "section::before,\r\n"
				+ ".card1::before{\r\n"
				+ "    content: '';\r\n"
				+ "    position: absolute;\r\n"
				+ "    width: 200px;\r\n"
				+ "    height: 200px;\r\n"
				+ "    border-radius: 50% 20px;\r\n"
				+ "    opacity:.8;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "section::before{\r\n"
				+ "    top: 6%;\r\n"
				+ "    left: 75%;\r\n"
				+ "    background: linear-gradient(#AAFFA9, #11FFBD);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".card1::before{\r\n"
				+ "    bottom:2%;\r\n"
				+ "    left: 10%;\r\n"
				+ "    background: linear-gradient(#0098f0, #0457d3);\r\n"
				+ "}\r\n"
				+ ".card {\r\n"
				+ "    display: flex;\r\n"
				+ "    flex-direction: row;\r\n"
				+ "    justify-content: space-between;\r\n"
				+ "    align-items: center;\r\n"
				+ "    border-radius: 30px;\r\n"
				+ "    padding: 10px;\r\n"
				+ "    box-shadow: 0px 0px 5px rgba(0, 0, 0, 0.2);\r\n"
				+ "    width: 900px;\r\n"
				+ "    height: 480px;\r\n"
				+ "    box-shadow: 0 15px 35px rgba(0,0,0,0.5);\r\n"
				+ "    background-color: rgba(255,255,255,0.05);\r\n"
				+ "    filter: blur(0.2px);\r\n"
				+ "}\r\n"
				+ ".left-container {\r\n"
				+ "    flex: 1;\r\n"
				+ "    max-width: 30%;\r\n"
				+ "    display: flex;\r\n"
				+ "    flex-direction: column;\r\n"
				+ "    align-items: center;\r\n"
				+ "    height:100%;\r\n"
				+ "    padding: 10px;\r\n"
				+ "    margin: 30px;\r\n"
				+ "    border-right: 1px solid #e4e4e4;\r\n"
				+ "  }\r\n"
				+ "  \r\n"
				+ "  .right-container {\r\n"
				+ "    flex: 1;\r\n"
				+ "    max-width:70%;\r\n"
				+ "    height:430px;\r\n"
				+ "    padding: 10px;\r\n"
				+ "    margin: 20px;\r\n"
				+ "    border-radius:30px;\r\n"
				+ "  }\r\n"
				+ "  @media only screen and (max-width: 860px) {\r\n"
				+ "    .card\r\n"
				+ "     {\r\n"
				+ "     flex-direction: column;\r\n"
				+ "     margin: 10px;\r\n"
				+ "     height: auto;\r\n"
				+ "     width: 100%;\r\n"
				+ "    }\r\n"
				+ "    .left-container{\r\n"
				+ "        flex: 1;\r\n"
				+ "        max-width:100%; \r\n"
				+ "        border:none;\r\n"
				+ "    }\r\n"
				+ " section::before{\r\n"
				+ "        top:4%;\r\n"
				+ "        left:51%;\r\n"
				+ "    }\r\n"
				+ "  }\r\n"
				+ "  @media only screen and (max-width: 600px) {\r\n"
				+ "    .card\r\n"
				+ "     {\r\n"
				+ "     flex-direction: column;\r\n"
				+ "     margin: 10px;\r\n"
				+ "    }\r\n"
				+ "    .left-container{\r\n"
				+ "        flex: 1;\r\n"
				+ "        max-width:100%; \r\n"
				+ "    }\r\n"
				+ "    .card1::before{\r\n"
				+ "        bottom: -14%;\r\n"
				+ "        left: 1%;\r\n"
				+ "    }\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "  }\r\n"
				+ "  img {\r\n"
				+ "    border: double 5px transparent;\r\n"
				+ "    border-radius: 50%;\r\n"
				+ "    background-image: linear-gradient(white, white), \r\n"
				+ "                      linear-gradient(to right, #ee00ff,#fbff00);\r\n"
				+ "    background-origin: border-box;\r\n"
				+ "    background-clip: content-box, border-box;\r\n"
				+ "    width: 200px;\r\n"
				+ "    height: 200px;\r\n"
				+ "    max-width: 200px;\r\n"
				+ "    margin-top: 70px;\r\n"
				+ "  }\r\n"
				+ "  \r\n"
				+ "  h2 {\r\n"
				+ "    font-size: 24px;\r\n"
				+ "    margin-bottom: 5px;\r\n"
				+ "  }\r\n"
				+ "  h3 {\r\n"
				+ "    text-align: center;\r\n"
				+ "    font-size: 24px;\r\n"
				+ "    margin-bottom: 5px;\r\n"
				+ "  }\r\n"
				+ "  .gradienttext{\r\n"
				+ "    background-image: linear-gradient(to right, #00c6ff 0%, #0072ff 100%);\r\n"
				+ "    color: transparent;\r\n"
				+ "    -webkit-background-clip: text;\r\n"
				+ "  }\r\n"
				+ "  .social-icons {\r\n"
				+ "    display: flex;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    align-items: center;\r\n"
				+ "  }\r\n"
				+ "  \r\n"
				+ "  .social-icons a {\r\n"
				+ "    background-image: linear-gradient(to right, #00c6ff 0%, #0072ff 100%);\r\n"
				+ "    display: inline-block;\r\n"
				+ "    margin-right: 15px;\r\n"
				+ "    padding:15px ;\r\n"
				+ "    width:30px;\r\n"
				+ "    height:30px;\r\n"
				+ "    border-radius:30px;\r\n"
				+ "    text-align: center;\r\n"
				+ "  }\r\n"
				+ "  \r\n"
				+ "  .social-icons i {\r\n"
				+ "    font-size: 24px;\r\n"
				+ "    color:rgba(255, 255, 255, .7);\r\n"
				+ "    transition: all 0.3s ease;\r\n"
				+ "  }\r\n"
				+ "  \r\n"
				+ "  .social-icons i:hover {\r\n"
				+ "    color: rgba(255, 255, 255, 1);\r\n"
				+ "  }\r\n"
				+ "  p {\r\n"
				+ "    font-size: 18px;\r\n"
				+ "    margin-bottom: 20px;\r\n"
				+ "    color:aliceblue\r\n"
				+ "  }\r\n"
				+ "  \r\n"
				+ "  table {\r\n"
				+ "    display: flex;\r\n"
				+ "    flex-direction: column;\r\n"
				+ "    justify-content: center;\r\n"
				+ "    align-items: center;\r\n"
				+ "    width: 100%;\r\n"
				+ "    height: 280px;\r\n"
				+ "    border-collapse: collapse;\r\n"
				+ "  }\r\n"
				+ "  \r\n"
				+ "  td {\r\n"
				+ "    \r\n"
				+ "    padding: 10px;\r\n"
				+ "    border: none;\r\n"
				+ "    border-radius: 20px;\r\n"
				+ "    color: white;\r\n"
				+ "  }\r\n"
				+ "  \r\n"
				+ "  td:first-child {\r\n"
				+ "    font-weight: bold;\r\n"
				+ "  }\r\n"
				+ "  .credit a {\r\n"
				+ "  text-decoration: none;\r\n"
				+ "  color: #fff;\r\n"
				+ "  font-weight: 800;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".credit {\r\n"
				+ "    color: #fff;\r\n"
				+ "  text-align: center;\r\n"
				+ "  margin-top: 10px;\r\n"
				+ "  font-family: Verdana,Geneva,Tahoma,sans-serif;\r\n"
				+ "}</style>"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "    <section>\r\n"
				+ "        <div class=\"card1\">\r\n"
				+ "            <div class=\"card\">\r\n"
				+ "                <div class=\"left-container\">\r\n"
				+ "                  <img src=\"https://upload.wikimedia.org/wikipedia/commons/2/2f/Logo_NTU.png\" alt=\"Profile Image\">\r\n"
				+ "                  <h2 class=\"gradienttext\">Nguyễn Minh Quang</h2>\r\n"
				+ "                  <p>Lập trình viên</p>\r\n"
				+ "                </div>\r\n"
				+ "                <div class=\"right-container\">\r\n"
				+ "                  <h3 class=\"gradienttext\">Profile</h3>\r\n"
				+ "                  <table>\r\n"
				+ "                      <tr>\r\n"
				+ "                          <td>Name :</td>\r\n"
				+ "                          <td>Nguyễn Minh Quang</td>\r\n"
				+ "                        </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td>Age :</td>\r\n"
				+ "                      <td>21</td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td>Mobile :</td>\r\n"
				+ "                      <td>0394642365</td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td>Email :</td>\r\n"
				+ "                      <td>quang.nm.64cntt@ntu.edu.vn</td>\r\n"
				+ "                    </tr>\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td>Address :</td>\r\n"
				+ "                      <td>Thị Trấn, Diên Khánh, Khánh Hòa</td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                  <div class=\"social-icons\">\r\n"
				+ "                    <a href=\"#\"><i class=\"fa fa-facebook-f\"></i></a>\r\n"
				+ "                    <a href=\"#\"><i class=\"fa fa-github\"></i></a>\r\n"
				+ "                  </div>\r\n"
				+ "                </div>\r\n"
				+ "              </div>\r\n"
				+ "        </div>\r\n"
				+ "    </section>\r\n"
				+ "      \r\n"
				+ "</body>\r\n"
				+ "</html>";
			wt.append(value);
	}

}
